version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: medods
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "dockerize -wait tcp://db:5432 -timeout 30s && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0"]
